version: '3.7'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: password
      POSTGRES_USER: yurtaevasofia
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - 5432:5432
